spring.application.name=api-gateway
server.port=8080

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.server.webmvc.routes[0].id=pacientes-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=${GATEWAY_PACIENTES_URI:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/pacientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=medicos-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=${GATEWAY_MEDICOS_URI:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/medicos/**

spring.cloud.gateway.server.webmvc.routes[2].id=citas-service-route
spring.cloud.gateway.server.webmvc.routes[2].uri=${GATEWAY_CITAS_URI:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/citas/**
