spring.application.name=citas-service
server.port=8083

spring.datasource.url=jdbc:h2:mem:citasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

external.services.pacientes-base-url=http://localhost:8081
external.services.medicos-base-url=http://localhost:8082
